name: adilabad_autos_cabs

description: AdilabadAutoCabs - A Flutter app with Firebase integration.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.17.6
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.2.3
  shared_preferences: ^2.5.3
  workmanager: ^0.5.2
  youtube_player_iframe: ^5.1.3
  url_launcher: ^6.3.0
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  extension_google_sign_in_as_googleapis_auth: ^2.0.13
  file_picker: ^8.0.7
  http: ^1.5.0
  minio: ^3.5.8  # S3-compatible client for Cloudflare R2
  path_provider: ^2.1.3
  path: ^1.8.3
  open_filex: ^4.6.0
  _discoveryapis_commons: ^1.0.7
  video_compress: ^3.1.3
  video_player: ^2.9.2
  video_thumbnail: ^0.5.3
  background_downloader: ^9.2.3
  permission_handler: ^11.3.1
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.2.8
  flutter_isolate: ^2.0.4
  intl: ^0.20.2
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  dotted_border: ^2.1.0
  cached_network_image: ^3.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
