// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLWNYTlLJMId9d-fQR4BMnOwwXwfoC51Y',
    appId: '1:402790849608:web:285aa53c3a1eb32902cc7d',
    messagingSenderId: '402790849608',
    projectId: 'adilabadautocabs',
    authDomain: 'adilabadautocabs.firebaseapp.com',
    databaseURL: 'https://adilabadautocabs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adilabadautocabs.appspot.com',
    measurementId: 'G-VHZ5LT8DTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7wD5in4xp1u8R0zq9jMiCr9NW0TnHqCo',
    appId: '1:402790849608:android:211adb63db4aeca002cc7d',
    messagingSenderId: '402790849608',
    projectId: 'adilabadautocabs',
    databaseURL: 'https://adilabadautocabs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adilabadautocabs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaf7L646dxIr8YY4pSbi3HL6I5XpVsMuQ',
    appId: '1:402790849608:ios:e3dadea7edce7cf702cc7d',
    messagingSenderId: '402790849608',
    projectId: 'adilabadautocabs',
    databaseURL: 'https://adilabadautocabs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adilabadautocabs.appspot.com',
    androidClientId: '402790849608-brdnbq1a4a2r11pmp1vu2bvu7i1q2s8a.apps.googleusercontent.com',
    iosBundleId: 'com.adbsmalltech.adbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaf7L646dxIr8YY4pSbi3HL6I5XpVsMuQ',
    appId: '1:402790849608:ios:e3dadea7edce7cf702cc7d',
    messagingSenderId: '402790849608',
    projectId: 'adilabadautocabs',
    databaseURL: 'https://adilabadautocabs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adilabadautocabs.appspot.com',
    androidClientId: '402790849608-brdnbq1a4a2r11pmp1vu2bvu7i1q2s8a.apps.googleusercontent.com',
    iosBundleId: 'com.adbsmalltech.adbapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLWNYTlLJMId9d-fQR4BMnOwwXwfoC51Y',
    appId: '1:402790849608:web:3ea54d01f74ea22002cc7d',
    messagingSenderId: '402790849608',
    projectId: 'adilabadautocabs',
    authDomain: 'adilabadautocabs.firebaseapp.com',
    databaseURL: 'https://adilabadautocabs-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'adilabadautocabs.appspot.com',
    measurementId: 'G-8LS7CGJHKJ',
  );
}
